// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiobYUU-vRQiM151nxQqg_MJxHLP9BmbU',
    appId: '1:7076195563:android:0ed8cbd112eabb1bcb62ae',
    messagingSenderId: '7076195563',
    projectId: 'flutter-video-audio-chat-1c489',
    storageBucket: 'flutter-video-audio-chat-1c489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVEG2S8xDa0sJTARqaQmuWpmHH3oxm80A',
    appId: '1:7076195563:ios:e41b0e9f6c84284dcb62ae',
    messagingSenderId: '7076195563',
    projectId: 'flutter-video-audio-chat-1c489',
    storageBucket: 'flutter-video-audio-chat-1c489.appspot.com',
    iosClientId: '7076195563-cnsssnkopj8vee842neepjgr8r9c02p4.apps.googleusercontent.com',
    iosBundleId: 'com.dbestech.chatty',
  );
}
